Calendar at bottom of home page
ricardocarva/AgileMinds pull request #22
Opened 2024-10-22 20:36 UTC by Kstrella

Got the calendar to show but still need api integration

2024-10-23 03:48 UTC, ricardocarva approved these changes

2024-10-25 12:13 UTC, roc-ricardo requested changes

2024-10-25 12:13 UTC, roc-ricardo commented on AgileMindsUI/AgileMindsUI/AgileMindsUI.csproj
> +    <PackageReference Include="Heron.MudCalendar" Version="2.0.3" />
@Kstrella, can you do me a favor and remove this line from the commit as the package is used in the AgileMindsUI.Client project?

2024-10-25 12:13 UTC, roc-ricardo commented on AgileMindsUI/AgileMindsUI/Components/_Imports.razor
> +@using AgileMindsUI.Components
@Kstrella, can you do me a favor and remove this line from the commit as the package is used in the AgileMindsUI.Client project?

2024-10-25 12:13 UTC, roc-ricardo commented on AgileMindsUI/AgileMindsUI/Components/_Imports.razor
> +﻿﻿@using System.Net.Http
Is this needed for this Project as the changes of this commit were to the AgileMindsUI.Client?

2024-10-25 12:14 UTC, roc-ricardo commented
@Kstrella great stuff, can you please commit the changes and push it again please? Once merged, I will move them to the Projects.razor page that we're currently using in `main`.

2024-10-26 22:33 UTC, merged